[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app_free.py"

[variables]
PORT = "8000"

## 🔧 **SOLUCIÓN DEFINITIVA**

Debes **reemplazar completamente** el contenido del archivo `nixpacks.toml` con solo esto:
```toml
[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app_free.py"

[variables]
PORT = "8000"